"""add entry

Revision ID: 049427ef4cfa
Revises: 9580520095c1
Create Date: 2025-11-20 16:34:17.253476

"""

import sqlalchemy as sa
from alembic import (
    op,
)

# revision identifiers, used by Alembic.
revision = "049427ef4cfa"
down_revision = "9580520095c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entry",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "register_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["register_id"],
            ["register.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "entry",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entry_name"),
            ["name"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_entry_register_id"),
            ["register_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "entry",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entry_register_id"))
        batch_op.drop_index(batch_op.f("ix_entry_name"))

    op.drop_table("entry")
    # ### end Alembic commands ###
