"""add entry name to register unique constraint

Revision ID: 79610b132520
Revises: 049427ef4cfa
Create Date: 2025-11-20 16:48:49.960032

"""

import sqlalchemy as sa
from alembic import (
    op,
)

# revision identifiers, used by Alembic.
revision = "79610b132520"
down_revision = "049427ef4cfa"
branch_labels = (
    None
)
depends_on = (
    None
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "entry",
        schema=None,
    ) as batch_op:
        batch_op.create_unique_constraint(
            "_entry_name_register_uc",
            [
                "name",
                "register_id",
            ],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "entry",
        schema=None,
    ) as batch_op:
        batch_op.drop_constraint(
            "_entry_name_register_uc",
            type_="unique",
        )

    # ### end Alembic commands ###
