"""add register

Revision ID: 9580520095c1
Revises:
Create Date: 2025-11-13 11:33:52.718351

"""

import sqlalchemy as sa
from alembic import (
    op,
)

# revision identifiers, used by Alembic.
revision = "9580520095c1"
down_revision = (
    None
)
branch_labels = (
    None
)
depends_on = (
    None
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "register",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
    )
    with op.batch_alter_table(
        "register",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_register_name"
            ),
            [
                "name"
            ],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "register",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_register_name"
            )
        )

    op.drop_table(
        "register"
    )
    # ### end Alembic commands ###
