"""remove entry name uniqueness

Revision ID: e2e091996f1f
Revises: 79610b132520
Create Date: 2025-11-21 11:52:24.996638

"""

import sqlalchemy as sa
from alembic import (
    op,
)

# revision identifiers, used by Alembic.
revision = "e2e091996f1f"
down_revision = "79610b132520"
branch_labels = (
    None
)
depends_on = (
    None
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "entry",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_name"
            )
        )
        batch_op.create_index(
            batch_op.f(
                "ix_entry_name"
            ),
            [
                "name"
            ],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "entry",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_entry_name"
            )
        )
        batch_op.create_index(
            batch_op.f(
                "ix_entry_name"
            ),
            [
                "name"
            ],
            unique=True,
        )

    # ### end Alembic commands ###
